#!/bin/sh
# samurai — ninja-compatible build tool in C.
set -e
dest=$1
CC=${CC:-cc}

make CC="$CC" PREFIX=/usr
make PREFIX=/usr DESTDIR="$dest" install

# Provide a 'ninja' symlink so cmake -GNinja works.
busybox ln -sf samu "$dest/usr/bin/ninja"
