#!/bin/sh -e

make CC="$CC $CFLAGS -fPIC $LDFLAGS" -f Makefile-libbz2_so
make CC="$CC $CFLAGS -fPIC $LDFLAGS" bzip2

busybox mkdir -p \
    "$1/usr/bin" \
    "$1/usr/lib" \
    "$1/usr/share/man/man1" \
    "$1/usr/include"

busybox cp -f \
    bzip2 \
    bzdiff \
    bzgrep \
    bzmore \
    "$1/usr/bin"

busybox cp -f \
    libbz2.so.1.0.8 \
    libbz2.a \
    "$1/usr/lib"

busybox cp -f bzip2.1 "$1/usr/share/man/man1"
busybox cp -f bzlib.h "$1/usr/include"

busybox ln -sf libbz2.so.1.0.8 "$1/usr/lib/libbz2.so"
busybox ln -sf libbz2.so.1.0.8 "$1/usr/lib/libbz2.so.1"
busybox ln -sf libbz2.so.1.0.8 "$1/usr/lib/libbz2.so.1.0"
busybox ln -sf bzip2 "$1/usr/bin/bunzip2"
busybox ln -sf bzip2 "$1/usr/bin/bzcat"
