#!/bin/sh -e

BINOWN="$(id -u)" \
BINGRP="$(id -g)" \
./configure \
    --prefix=/usr \
    --with-shadow \
    --with-timestamp \
    --without-pam

make
make DESTDIR="$1" install

busybox mkdir -p "$1/etc"
busybox cp -f doas.conf "$1/etc"
busybox chmod 600 "$1/etc/doas.conf"
