#!/bin/sh -e

export CPPFLAGS="$CPPFLAGS -DSQLITE_ENABLE_COLUMN_METADATA=1"

./configure \
    --prefix=/usr \
    --enable-threadsafe \
    --enable-dynamic-extensions \
    --enable-fts5 \
    ac_cv_search_readline=no

make
make install
