#!/bin/sh -e

./configure \
    --prefix=/usr

# Fix gnulib _GL_ATTRIBUTE_NODISCARD incompatibility with newer GCC.
# The [[__nodiscard__]] attribute in GL_OSET_INLINE context confuses the parser.
find lib -name '*.h' -exec sed -i \
    's/^\(# *define _GL_ATTRIBUTE_NODISCARD\) .*/\1/' {} +

make
make install
