#!/bin/sh -e

cmake -GNinja -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_TESTING=OFF \
    -DCMAKE_C_COMPILER="${CC:-cc}" \
    -DCMAKE_CXX_COMPILER="${CXX:-c++}"
ninja -C build

mkdir -p "$1/usr/lib/pkgconfig" "$1/usr/include" "$1/etc/ssl"

cp -r include/openssl "$1/usr/include/"
cp build/libssl.so "$1/usr/lib/"
cp build/libcrypto.so "$1/usr/lib/"

cp -f update-certdata.sh "$1/etc/ssl"

# pkg-config files for curl and other consumers.
cat > "$1/usr/lib/pkgconfig/libssl.pc" <<EOF
prefix=/usr
libdir=\${prefix}/lib
includedir=\${prefix}/include

Name: libssl
Description: BoringSSL
Version: 0.0.0
Libs: -L\${libdir} -lssl -lcrypto
Cflags: -I\${includedir}
EOF

cat > "$1/usr/lib/pkgconfig/libcrypto.pc" <<EOF
prefix=/usr
libdir=\${prefix}/lib
includedir=\${prefix}/include

Name: libcrypto
Description: BoringSSL
Version: 0.0.0
Libs: -L\${libdir} -lcrypto
Cflags: -I\${includedir}
EOF

cat > "$1/usr/lib/pkgconfig/openssl.pc" <<EOF
prefix=/usr

Name: openssl
Description: BoringSSL (OpenSSL-compatible)
Version: 0.0.0
Requires: libssl libcrypto
EOF
