#!/bin/sh
# go — precompiled Go toolchain from go.dev.
# pm strips the top-level directory, so bin/, src/, pkg/ are in $PWD.
set -e
dest=$1

busybox mkdir -p "$dest/usr/lib/go"
busybox cp -a . "$dest/usr/lib/go"

busybox mkdir -p "$dest/usr/bin"
busybox ln -s ../lib/go/bin/go "$dest/usr/bin/go"
busybox ln -s ../lib/go/bin/gofmt "$dest/usr/bin/gofmt"

busybox mkdir -p "$dest/etc/profile.d"
busybox cp -f go.sh "$dest/etc/profile.d/"
