#!/bin/sh -e
dest=$1

# Bootstrap muon from the amalgamated source.
CC=cc sh bootstrap.sh build

# Use the bootstrapped muon to build itself properly.
build/muon-bootstrap setup \
    -Dprefix=/usr \
    -Dlibcurl=disabled \
    -Dlibarchive=disabled \
    -Dlibpkgconf=disabled \
    -Dman-pages=disabled \
    -Dmeson-docs=disabled \
    -Dmeson-tests=disabled \
    -Dwebsite=disabled \
    build-final

samu -C build-final
DESTDIR="$dest" build/muon-bootstrap -C build-final install
