#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc

make
make DESTDIR="$1" install

busybox ln -s pkgconf "$1/usr/bin/pkg-config"

# Remove documentation.
busybox rm -rf "$1/usr/share/doc"
