#!/bin/sh -e

cd runit-2.1.2

# Override compiler and linker.
echo "${CC:-cc} -O2 -Wall -D_GNU_SOURCE -Wno-implicit-function-declaration -Wno-incompatible-pointer-types" > src/conf-cc
echo "${CC:-cc} -s"        > src/conf-ld

# runit defaults to -static; remove it for dynamic linking.
busybox sed -i 's/ -static//g' src/Makefile

# Build using runit's own build system.
package/compile

# Install supervision binaries.
busybox mkdir -p "$1/usr/bin"
for bin in chpst runsv runsvdir sv svlogd; do
    busybox cp -f "command/$bin" "$1/usr/bin/"
done
