#!/bin/sh -e

busybox mkdir -m 755 \
    "$1/boot" \
    "$1/dev" \
    "$1/etc" \
    "$1/home" \
    "$1/mnt" \
    "$1/opt" \
    "$1/run" \
    "$1/usr" \
    "$1/usr/bin" \
    "$1/usr/include" \
    "$1/usr/lib" \
    "$1/usr/share" \
    "$1/usr/share/man" \
    "$1/usr/share/man/man1" \
    "$1/usr/share/man/man2" \
    "$1/usr/share/man/man3" \
    "$1/usr/share/man/man4" \
    "$1/usr/share/man/man5" \
    "$1/usr/share/man/man6" \
    "$1/usr/share/man/man7" \
    "$1/usr/share/man/man8" \
    "$1/var/cache" \
    "$1/var/local" \
    "$1/var/opt" \
    "$1/var/log" \
    "$1/var/log/old" \
    "$1/var/lib" \
    "$1/var/lib/misc" \
    "$1/var/empty" \
    "$1/var/service" \
    "$1/var/spool"

busybox mkdir -m 555 \
    "$1/proc" \
    "$1/sys"

busybox mkdir -m 0750 \
    "$1/root"

busybox mkdir -m 1777 \
    "$1/tmp" \
    "$1/var/tmp" \
    "$1/var/spool/mail"

busybox ln -sf usr/bin "$1/bin"
busybox ln -sf usr/bin "$1/sbin"
busybox ln -sf bin     "$1/usr/sbin"
busybox ln -sf usr/lib "$1/lib"
busybox ln -sf usr/lib "$1/lib64"

busybox ln -sf lib               "$1/usr/lib64"
busybox ln -sf spool/mail        "$1/var/mail"
busybox ln -sf ../run            "$1/var/run"
busybox ln -sf ../run/lock       "$1/var/lock"
busybox ln -sf /proc/self/mounts "$1/etc/mtab"

busybox cp -f ./* "$1/etc"

busybox chmod 600 \
    "$1/etc/crypttab" \
    "$1/etc/shadow"
