#!/bin/sh -e

# Ensure configure can find headers and libraries in KOMINKA_ROOT.
if [ -n "$KOMINKA_ROOT" ] && [ "$KOMINKA_ROOT" != "/" ]; then
    CFLAGS="${CFLAGS:--O2 -DNDEBUG} -I${KOMINKA_ROOT}/usr/include -Wno-error -include time.h"
    LDFLAGS="${LDFLAGS:-} -L${KOMINKA_ROOT}/usr/lib"
    export CFLAGS LDFLAGS
fi

./configure \
    --prefix=/usr \
    --enable-ipv6 \
    --enable-unix-sockets \
    --enable-hidden-symbols \
    --disable-manual \
    --disable-ldap \
    --disable-ares \
    --with-openssl="${KOMINKA_ROOT:-}/usr" \
    --with-pic \
    --with-ca-fallback \
    --without-librtmp \
    --without-icu \
    --without-libpsl \
    --without-libidn \
    --without-libidn2 \
    --without-brotli \
    --without-zstd

make
make DESTDIR="$1" install
