#!/bin/sh -e

# curl 7.80.0 is missing #include <time.h> in altsvc.c — patch it.
sed -i '1i #include <time.h>' lib/altsvc.c
CFLAGS="${CFLAGS:--O2 -DNDEBUG} -Wno-error -D_GNU_SOURCE"
LDFLAGS="${LDFLAGS:-}"
CPPFLAGS=""

if [ -n "$KOMINKA_ROOT" ] && [ "$KOMINKA_ROOT" != "/" ]; then
    CPPFLAGS="-I${KOMINKA_ROOT}/usr/include"
    LDFLAGS="${LDFLAGS} -L${KOMINKA_ROOT}/usr/lib"
fi
export CFLAGS LDFLAGS CPPFLAGS

./configure \
    --prefix=/usr \
    --enable-ipv6 \
    --enable-unix-sockets \
    --enable-hidden-symbols \
    --disable-manual \
    --disable-ldap \
    --disable-ares \
    --with-openssl="${KOMINKA_ROOT:-}/usr" \
    --with-pic \
    --with-ca-fallback \
    --without-librtmp \
    --without-icu \
    --without-libpsl \
    --without-libidn \
    --without-libidn2 \
    --without-brotli \
    --without-zstd

make
make DESTDIR="$1" install
