#!/bin/sh -e


cat > config.mak <<EOF
NO_GETTEXT=YesPlease
NO_SVN_TESTS=YesPlease
NO_TCLTK=YesPlease
NO_EXPAT=YesPlease
NO_NSEC=YesPlease
NO_PYTHON=YesPlease
NO_PERL=YesPlease
NO_SYS_POLL_H=1
NO_CROSS_DIRECTORY_HARDLINKS=1
NO_INSTALL_HARDLINKS=1
EOF

if [ -n "$KOMINKA_ROOT" ] && [ "$KOMINKA_ROOT" != "/" ]; then
    export CPPFLAGS="-I${KOMINKA_ROOT}/usr/include"
    export LDFLAGS="-L${KOMINKA_ROOT}/usr/lib"
fi

./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    ac_cv_lib_curl_curl_global_init=yes \
    ac_cv_snprintf_returns_bogus=no \
    ac_cv_fread_reads_directories=yes

make LDFLAGS="$LDFLAGS" LIBS="-lcurl -lssl -lcrypto libgit.a xdiff/lib.a -lz"
make DESTDIR="$1" install

# Install manpages if downloaded.
if [ -d man ]; then
    mkdir -p "$1/usr/share/man"
    cp -Rf man "$1/usr/share/"
fi
